//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLand.GameLandWebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gameland.com/", ConfigurationName="GameLandWebServiceRef.GameServiceSoap")]
    public interface GameServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/RegisterUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RegisterUser(string name, string ic, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RegisterUserAsync(string name, string ic, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/LoginUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoginUser(string ic, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/LoginUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginUserAsync(string ic, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/CalculateCharge", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double CalculateCharge(double hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/CalculateCharge", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculateChargeAsync(double hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/CheckConnectionString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckConnectionString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/CheckConnectionString", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckConnectionStringAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GameServiceSoapChannel : GameLand.GameLandWebServiceRef.GameServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceSoapClient : System.ServiceModel.ClientBase<GameLand.GameLandWebServiceRef.GameServiceSoap>, GameLand.GameLandWebServiceRef.GameServiceSoap {
        
        public GameServiceSoapClient() {
        }
        
        public GameServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegisterUser(string name, string ic, string password) {
            return base.Channel.RegisterUser(name, ic, password);
        }
        
        public System.Threading.Tasks.Task<string> RegisterUserAsync(string name, string ic, string password) {
            return base.Channel.RegisterUserAsync(name, ic, password);
        }
        
        public string LoginUser(string ic, string password) {
            return base.Channel.LoginUser(ic, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginUserAsync(string ic, string password) {
            return base.Channel.LoginUserAsync(ic, password);
        }
        
        public double CalculateCharge(double hours) {
            return base.Channel.CalculateCharge(hours);
        }
        
        public System.Threading.Tasks.Task<double> CalculateChargeAsync(double hours) {
            return base.Channel.CalculateChargeAsync(hours);
        }
        
        public string CheckConnectionString() {
            return base.Channel.CheckConnectionString();
        }
        
        public System.Threading.Tasks.Task<string> CheckConnectionStringAsync() {
            return base.Channel.CheckConnectionStringAsync();
        }
    }
}
