//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLand.GameLandWebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gameland.com/", ConfigurationName="GameLandWebServiceRef.GameServiceSoap")]
    public interface GameServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloResult from namespace http://gameland.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/Hello", ReplyAction="*")]
        GameLand.GameLandWebServiceRef.HelloResponse Hello(GameLand.GameLandWebServiceRef.HelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/Hello", ReplyAction="*")]
        System.Threading.Tasks.Task<GameLand.GameLandWebServiceRef.HelloResponse> HelloAsync(GameLand.GameLandWebServiceRef.HelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/CalculateCharge", ReplyAction="*")]
        double CalculateCharge(double hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gameland.com/CalculateCharge", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculateChargeAsync(double hours);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hello", Namespace="http://gameland.com/", Order=0)]
        public GameLand.GameLandWebServiceRef.HelloRequestBody Body;
        
        public HelloRequest() {
        }
        
        public HelloRequest(GameLand.GameLandWebServiceRef.HelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloRequestBody {
        
        public HelloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloResponse", Namespace="http://gameland.com/", Order=0)]
        public GameLand.GameLandWebServiceRef.HelloResponseBody Body;
        
        public HelloResponse() {
        }
        
        public HelloResponse(GameLand.GameLandWebServiceRef.HelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://gameland.com/")]
    public partial class HelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloResult;
        
        public HelloResponseBody() {
        }
        
        public HelloResponseBody(string HelloResult) {
            this.HelloResult = HelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GameServiceSoapChannel : GameLand.GameLandWebServiceRef.GameServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceSoapClient : System.ServiceModel.ClientBase<GameLand.GameLandWebServiceRef.GameServiceSoap>, GameLand.GameLandWebServiceRef.GameServiceSoap {
        
        public GameServiceSoapClient() {
        }
        
        public GameServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameLand.GameLandWebServiceRef.HelloResponse GameLand.GameLandWebServiceRef.GameServiceSoap.Hello(GameLand.GameLandWebServiceRef.HelloRequest request) {
            return base.Channel.Hello(request);
        }
        
        public string Hello() {
            GameLand.GameLandWebServiceRef.HelloRequest inValue = new GameLand.GameLandWebServiceRef.HelloRequest();
            inValue.Body = new GameLand.GameLandWebServiceRef.HelloRequestBody();
            GameLand.GameLandWebServiceRef.HelloResponse retVal = ((GameLand.GameLandWebServiceRef.GameServiceSoap)(this)).Hello(inValue);
            return retVal.Body.HelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameLand.GameLandWebServiceRef.HelloResponse> GameLand.GameLandWebServiceRef.GameServiceSoap.HelloAsync(GameLand.GameLandWebServiceRef.HelloRequest request) {
            return base.Channel.HelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameLand.GameLandWebServiceRef.HelloResponse> HelloAsync() {
            GameLand.GameLandWebServiceRef.HelloRequest inValue = new GameLand.GameLandWebServiceRef.HelloRequest();
            inValue.Body = new GameLand.GameLandWebServiceRef.HelloRequestBody();
            return ((GameLand.GameLandWebServiceRef.GameServiceSoap)(this)).HelloAsync(inValue);
        }
        
        public double CalculateCharge(double hours) {
            return base.Channel.CalculateCharge(hours);
        }
        
        public System.Threading.Tasks.Task<double> CalculateChargeAsync(double hours) {
            return base.Channel.CalculateChargeAsync(hours);
        }
    }
}
